### ISSUE TITLE
another package with the same name

### ISSUE THREAD

**Issue by lincolnfrias** [jzuccollo/pyDEA#9]
Are you aware that there is [another package with the same name](https://github.com/araith/pyDEA/). And when installing with `pip install pydea` we get that other package, not yours.   

This is awful given that your package is the best way to do development analysis in python that I am aware of (we are using it on a master thesis in public management I am advising). Thanks for your work.

**Comment by jzuccollo** [comment]
Thanks @lincolnfrias for getting in touch about this and sorry for the slow reply: I managed to lock myself out of my account for a few weeks! Since my package is no longer actively maintained, I won't be trying to reclaim the name from them but thanks for drawing it to my attention.
